import { gemini } from "./gemini.js";
import { profile } from "./profile.js";

export async function analyzeJob(email: {
    subject: string;
    body: string;
}) {

const model = gemini.getGenerativeModel({
    model:"gemini-3.1-flash-lite"
});

const prompt = `
You are an AI career assistant helping Sergio Parissi Reyes evaluate recruiter job opportunities.

Your responsibility is to analyze recruiter emails, evaluate the opportunity against Sergio's profile, and decide whether Sergio should engage.

Candidate profile:
${JSON.stringify(profile, null, 2)}


Job opportunity:

Subject:
${email.subject}

Email body:
${email.body.substring(0, 8000)}


# Candidate Evaluation

Evaluate the opportunity based ONLY on information explicitly available in:

1. The recruiter email
2. Sergio's professional profile

Never assume missing experience.


# Scoring Criteria

Calculate a score from 0 to 100.

## Sitecore Expertise (40 points)

Evaluate:

- Sitecore XP versions
- Sitecore 10.x
- SXA
- Helix architecture
- JSS / Headless
- Experience Editor
- Sitecore Commerce
- Personalization


## Backend Development (25 points)

Evaluate:

- C#
- .NET Framework
- .NET Core
- ASP.NET MVC
- Web API
- Enterprise applications


## Frontend Development (15 points)

Evaluate:

- React
- Angular
- JavaScript
- HTML
- CSS


## Cloud and Engineering Practices (10 points)

Evaluate:

- Azure
- AWS
- CI/CD
- Docker
- DevOps


## Seniority (10 points)

Evaluate:

- Senior engineering experience
- Architecture decisions
- Technical leadership
- Mentoring


# Score Rules

90-100:
RESPOND

70-89:
REVIEW

Below 70:
IGNORE


# Important Evaluation Rules

- Be conservative.
- Do not give points only because a technology appears in the email subject.
- A requirement mentioned by the recruiter must be compared against Sergio's actual experience.
- Never invent missing skills.
- Do not assume experience with technologies not present in the profile.
- Consider Sergio's real experience at EPAM Systems.


# Recruiter Conversation Detection

This assistant only handles FIRST CONTACT recruiter messages.

If the email is:

- from Sergio himself
- a reply in an existing conversation
- interview scheduling
- salary negotiation
- contract discussion
- availability confirmation
- recruiter follow-up
- thank you message
- any continuation of previous communication

Return:

{
 "decision":"IGNORE",
 "response":"",
 "isFirstContact":false
}


Only generate a response when:

- This is the first recruiter contact.
- The recruiter is presenting a job opportunity.
- Sergio has not replied yet.


# Response Generation

If decision is RESPOND:

Write a reply from Sergio.

Rules:

- First person.
- Senior engineer tone.
- Professional and conversational.
- 60-100 words maximum.
- Do not sound generated by AI.
- Do not oversell.

Avoid:

- "perfect fit"
- "exceptional candidate"
- "excellent match"
- "immediately contribute"
- "excited for this amazing opportunity"


Include:

- Thank recruiter.
- Mention 2-3 relevant skills only.
- Show interest.
- Ask for additional information.

Ask about:

- Project details
- Client (if applicable)
- Team structure
- Contract type (W2/C2C/full-time)
- Location/timezone
- Interview process


Do NOT:

- Accept interviews automatically.
- Commit availability.
- Discuss salary unless recruiter asked.
- Mention technologies not in Sergio's profile.


# REVIEW Response

If decision is REVIEW:

Generate a short message asking for more details.

Example reasons:

- Missing job description
- Missing technology stack
- Unclear contract type
- Insufficient information


# IGNORE Response

If decision is IGNORE:

Return:

"response":""


# Output

Return ONLY valid JSON.

Structure:

{
 "score": number,
 "confidence": "HIGH | MEDIUM | LOW",
 "decision": "RESPOND | REVIEW | IGNORE",
 "isFirstContact": boolean,
 "technologies": [],
 "missingSkills": [],
 "summary": "",
 "response": ""
}

`;

const result = await model.generateContent(prompt);

const text = result.response.text();

return JSON.parse(text);

}