import { gemini } from "./gemini.js";
import { profile } from "./profile.js";

const RETRYABLE_STATUS_CODES = [429, 503];

async function generateWithRetry(
    model: ReturnType<typeof gemini.getGenerativeModel>,
    prompt: string,
    maxRetries = 3
) {

    for (let attempt = 0; ; attempt++) {

        try {
            return await model.generateContent(prompt);
        }
        catch (error: any) {

            const isRetryable =
                RETRYABLE_STATUS_CODES.includes(error?.status);

            if (!isRetryable || attempt >= maxRetries) {
                throw error;
            }

            const delayMs = 1000 * 2 ** attempt;

            console.warn(
                `Gemini request failed (status ${error.status}), retrying in ${delayMs}ms...`
            );

            await new Promise(resolve => setTimeout(resolve, delayMs));
        }
    }
}

export async function analyzeJob(email: {
    subject: string;
    body: string;
}) {

    const model = gemini.getGenerativeModel({
        model: "gemini-3.1-flash-lite"
    });


    const prompt = `
You are an AI career assistant helping Sergio Parissi Reyes evaluate recruiter job opportunities.

Your responsibility is to analyze recruiter emails, evaluate the opportunity against Sergio's profile, and decide whether Sergio should engage.


Candidate profile:

${JSON.stringify(profile, null, 2)}


Job opportunity:

Subject:
${email.subject}

Email body:
${email.body.substring(0, 8000)}



# Candidate Evaluation

Evaluate the opportunity based ONLY on information explicitly available in:

1. The recruiter email
2. Sergio's professional profile

Never assume missing experience.



# Scoring Criteria

Calculate a score from 0 to 100.


## Sitecore Expertise (40 points)

Evaluate:

- Sitecore XP versions
- Sitecore 10.x
- SXA
- Helix architecture
- JSS / Headless
- Experience Editor
- Sitecore Commerce
- Personalization


## Backend Development (25 points)

Evaluate:

- C#
- .NET Framework
- .NET Core
- ASP.NET MVC
- Web API
- Enterprise applications


## Frontend Development (15 points)

Evaluate:

- React
- Angular
- JavaScript
- HTML
- CSS


## Cloud and Engineering Practices (10 points)

Evaluate:

- Azure
- AWS
- CI/CD
- Docker
- DevOps


## Seniority (10 points)

Evaluate:

- Senior engineering experience
- Architecture decisions
- Technical leadership
- Mentoring



# Score Rules

90-100:
RESPOND

70-89:
REVIEW

Below 70:
IGNORE



# Important Evaluation Rules

- Be conservative.
- Do not give points only because a technology appears in the email subject.
- Compare recruiter requirements against Sergio's actual profile.
- Never invent missing skills.
- Do not assume experience with technologies not present in the profile.
- Consider Sergio's experience at EPAM Systems.



# Recruiter Conversation Detection

This assistant only handles FIRST CONTACT recruiter messages.

If the email is:

- from Sergio himself
- a reply in an existing conversation
- interview scheduling
- salary negotiation
- contract discussion
- availability confirmation
- recruiter follow-up
- thank you message
- continuation of previous communication

Return:

{
 "decision":"IGNORE",
 "response":"",
 "isFirstContact":false
}


Only generate a response when:

- This is the first recruiter contact.
- The recruiter is presenting a job opportunity.
- Sergio has not replied yet.



# Response Generation

If decision is RESPOND:

Generate ONLY the email body.

Rules:

- Write in first person as Sergio.
- Senior engineer tone.
- Professional and conversational.
- 60-100 words maximum.
- Natural human writing.
- Do not sound generated by AI.
- Do not oversell.


Avoid:

- "perfect fit"
- "exceptional candidate"
- "excellent match"
- "immediately contribute"
- "excited for this amazing opportunity"


Include:

- Thank the recruiter.
- Mention 2-3 relevant skills only.
- Show interest.
- Ask for additional information.


Ask about:

- Project details
- Client (if applicable)
- Team structure
- Contract type (W2/C2C/full-time)
- Location/timezone
- Interview process



IMPORTANT:

Do NOT include:

- Email signature
- "Best regards"
- Sergio's name
- CV links
- LinkedIn links
- Phone numbers
- Contact information
- Any closing signature

The application will automatically append Sergio's signature and CV link.



Do NOT:

- Accept interviews automatically.
- Commit availability.
- Discuss salary unless recruiter asked.
- Mention technologies not in Sergio's profile.



# REVIEW Response

If decision is REVIEW:

Generate a short message asking for more details.



# IGNORE Response

If decision is IGNORE:

Return:

"response":""


# Output

Return ONLY valid JSON.

Do not wrap JSON in markdown.
Do not use triple backticks.


Structure:

{
 "score": number,
 "confidence": "HIGH | MEDIUM | LOW",
 "decision": "RESPOND | REVIEW | IGNORE",
 "isFirstContact": boolean,
 "technologies": [],
 "missingSkills": [],
 "summary": "",
 "response": ""
}

`;


    const result = await generateWithRetry(model, prompt);

    let text = result.response.text();

    // Limpieza por si Gemini devuelve markdown
    text = text
        .replace(/```json/g, "")
        .replace(/```/g, "")
        .trim();


    return JSON.parse(text);

}